theme: jekyll-theme-minimal

title: Haneul Yoo
description: Ph.D. student<br>U&I Lab, School of Computing, KAIST<br>[haneul.yoo@kaist.ac.kr](mailto:haneul.yoo@kaist.ac.kr)
logo: ./assets/photo1.png
google_analytics: G-016QN3TNY0
