# theme: jekyll-theme-minimal

# title: Haneul Yoo
# description: Ph.D. student<br>U&I Lab, School of Computing, KAIST<br>haneul.yoo@kaist.ac.kr
# logo: ./assets/photo1.png
# google_analytics: G-016QN3TNY0

remote_theme: BDHU/minimalist
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

url: https://haneul-yoo.github.io
repository: haneul-yoo/haneul-yoo.github.io
color-scheme: auto

title: Haneul Yoo
description: "Ph.D. student<br>U&I Lab, School of Computing, KAIST"
logo: "./assets/photo1.png"

search: true
search_full_content: true

sidebar:
  - name: Email
    icon: <i class="fas fa-fw fa-envelope-square"></i>
    link: "mailto:haneul.yoo@kaist.ac.kr"
  - name: Twitter
    icon: <i class="fab fa-fw fa-twitter-square"></i>
    url: "https://twitter.com/HaneulYoo13"
  - name: LinkedIn
    icon: <i class="fab fa-fw fa-linkedin"></i>
    url: "https://linkedin.com/in/haneulyoo"
  - name: GitHub
    icon: <i class="fab fa-fw fa-github"></i>
    link: "https://github.com/haneul-yoo"
